resources:
  - resources/namespace.yaml
  - resources/kafka-deployment.yaml
  - resources/kafka-service.yaml
  - ../master

namespace: kafkaml

configMapGenerator:
  - name: kafkaml-configmap
    behavior: merge
    literals:
      - brokers=kafka:9092
images:
  - name: kafka
    newName: docker.io/bitnami/kafka
    newTag: "3.3"
