resources:
  - "../base"

configMapGenerator:
  - name: federated-kafkaml-configmap
    behavior: merge
    literals:
      - federated.tensorflow.training.image=ertis/federated-kafka-ml-tensorflow_model_training:v1.1
      - federated.pytorch.training.image=ertis/federated-kafka-ml-pytorch_model_training:v1.1 # Non existing
      # - kml.cloud.brokers=kafka-cloud.broker:9092
      # - federated.data.brokers=kafka-federated.broker:9092

images:
  - name: federated-kafka-ml-backend
    newName: ertis/federated-kafka-ml-backend
    newTag: v1.1
  - name: federated-kafka-ml-data_control_logger
    newName: ertis/federated-kafka-ml-data_control_logger
    newTag: v1.1
  - name: federated-kafka-ml-model_control_logger
    newName: ertis/federated-kafka-ml-model_control_logger
    newTag: v1.1