resources:
  - "../v1.0"

configMapGenerator:
  - name: kafkaml-configmap
    behavior: merge
    literals:
      - tensorflow.training.image=ertis/kafka-ml-tensorflow_model_training-gpu:v1.0
      - tensorflow.inference.image=ertis/kafka-ml-tensorflow_model_inference-gpu:v1.0
      - pytorch.training.image=ertis/kafka-ml-pytorch_model_training-gpu:v1.0
      - pytorch.inference.image=ertis/kafka-ml-pytorch_model_inference-gpu:v1.0

images:
  - name: ertis/kafka-ml-pthexecutor
    newName: ertis/kafka-ml-pthexecutor-gpu
  - name: ertis/kafka-ml-tfexecutor
    newName: ertis/kafka-ml-tfexecutor-gpu
