resources:
  - "../v1.1"

configMapGenerator:
  - name: federated-kafkaml-configmap
    behavior: merge
    literals:
      - federated.tensorflow.training.image=ertis/federated-kafka-ml-tensorflow_model_training-gpu:v1.1
      - federated.pytorch.training.image=ertis/federated-kafka-ml-pytorch_model_training-gpu:v1.1 # Non existing
      # - kml.cloud.brokers=kafka-cloud.broker:9092
      # - federated.data.brokers=kafka-federated.broker:9092
