# Based on https://github.com/ertis-research/fission-environments/blob/ecabe4ece71be5b12c8f3087bcbeae2062b239e2/.github/workflows/build.yml
on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      name:
        required: true
        type: string
      platforms:
        required: false
        type: string
        default: "linux/amd64"
      build-args:
        required: false
        type: string

env:
  # REGISTRY: ghcr.io
  USERNAME: ertis
  IMAGE_NAME: ${{ inputs.name }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          # registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}
      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ inputs.build-args }}
